version: '3'

services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master-container
    build:
      context: .
      dockerfile: Dockerfile
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./hdfs:/hdfs
    networks:
      - spark-network

  spark-worker:
    image: spark-master:latest
    container_name: spark-worker-container
    build:
      context: .
      dockerfile: Dockerfile
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=5G
      - SPARK_WORKER_CORES=3
    volumes:
      - ./hdfs:/hdfs
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    container_name: jupyter-container
    build:
      context: .
      dockerfile: Dockerfile2
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=admin123admin
    ports:
      - '8888:8888'
    volumes:
      - ./hdfs:/hdfs
    working_dir: /hdfs
    command: >
      start-notebook.sh --ip 0.0.0.0 --port 8888 
      --NotebookApp.token='admin123admin' 
      --NotebookApp.password='admin123admin'
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network

  minio:
    container_name: minio-container
    image: minio/minio:latest
    command: server --console-address ":9001" /minio-data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./minio-data:/minio-data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  hdfs:
  minio-data:
