version: '3'

services:
  spark:
    container_name: spark-master-container
    image: docker.io/bitnami/spark:3.5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    volumes:
      - ./hdfs:/hdfs


  spark-worker:
    container_name: spark-worker-container
    image: docker.io/bitnami/spark:3.5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-container:7077
      - SPARK_WORKER_MEMORY=5G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./hdfs:/hdfs

  jupyter:
    container_name: jupyter-container
    image: jupyter/pyspark-notebook:spark-3.5.0
    build:
      context: .
      dockerfile: Dockerfile2
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=admin123admin
    ports:
      - '8888:8888'
    volumes:
      - ./hdfs:/hdfs
    working_dir: /hdfs
    command: >
      start-notebook.sh --ip 0.0.0.0 --port 8888 --NotebookApp.token='admin123admin' --NotebookApp.password='admin123admin'
    depends_on:
      - spark
      - spark-worker
    

  minio:
    container_name: minio-container
    image: quay.io/minio/minio:RELEASE.2023-11-15T20-43-25Z.fips
    platform: linux/x86_64
    command: server --console-address ":9001" /minio-data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./minio-data:/minio-data

volumes:
  hdfs:
  minio-data:
